### ISSUE TITLE
Running Confluent Control Center against Azure Event Hubs

### ISSUE THREAD

**Issue by chinwobble** [confluentinc/examples#866]
Is it possible to run the Confluent Control Center against Azure Event Hubs Kafka API?

I am running kafka connect in Azure app service as a container and my docker-compose file looks like this:
```yaml
---
version: "2"
services:
  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.0
    hostname: control-center
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: demo-eventhubs-pl.servicebus.windows.net:9093
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: "connect:8083"
      CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL: SASL_SSL
      CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG: $CONN_STRING
      CONTROL_CENTER_STREAMS_SASL_MECHANISM: PLAIN
      CONTROL_CENTER_REST_LISTENERS: "http://localhost:9021"

  connect:
    build: ./connect
    hostname: connect
    container_name: connect
    stdin_open: true
    tty: true
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: demo-eventhubs-pl.servicebus.windows.net:9093
      CONNECT_GROUP_ID: "connect-cluster-group"
      CONNECT_REST_PORT: 8083
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-cluster-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-cluster-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-cluster-status"
      # internal topic replication factors - auto 3x replication in Azure Storage
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1

      REST_ADVERTISED_HOST_NAME: CONNECT
      OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      # CONNECT_REST_ADVERTISED_HOST_NAME: "default-config"
      # required EH Kafka security settings
      CONNECT_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_SASL_MECHANISM: "PLAIN"
      CONNECT_SASL_JAAS_CONFIG: $CONN_STRING

      CONNECT_PRODUCER_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_PRODUCER_SASL_MECHANISM: "PLAIN"

      CONNECT_PRODUCER_SASL_JAAS_CONFIG: $CONN_STRING

      CONNECT_CONSUMER_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_CONSUMER_SASL_MECHANISM: "PLAIN"

      CONNECT_CONSUMER_SASL_JAAS_CONFIG: $CONN_STRING
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_PLUGIN_PATH: "/usr/share/java/,/usr/share/confluent-hub-components/"
```

My kafka-connect container is working but the confluent control center is not.
Any help would be appreciated.
